server:
  context-path: /
  port: 8001
  tomcat:
    access_log_enabled: true
eureka:
  instance:
    hostname: gateway
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 10.8.0.
  application:
    name: gateway-service    

zuul:
  routes:
    users:
      path: /users/**
      serviceId: user-service    
    projects:
      path: /projects/**  
      serviceId: project-service