server:
  context-path: /
  port: 8801
  tomcat:
    access_log_enabled: true
eureka:
  instance:
    hostname: user
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
feign:
  hystrix:
    enabled: true
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 10.8.0.
  application:
    name: business-sop    
 
swagger:
  basePackage: com.galaxyinternet.sop.core.web
  title: SOP RESTful API
  desc: SOP RESTFUL API
  serviceUrl: http://www.galaxyinternet.com
  version: 1.0

oauth:
  authLocation: http://authserver.com/sso/authorize
  tokenLocation: http://authserver.com/sso/token
  meLocation: http://authserver.com/sso/me
  client_id: 1
  client_secret: 111
  redirect_uri: http://sop.com:8801/