debug: false
server:
  context-path: /sso
  port: 80
  tomcat:
    access_log_enabled: true
eureka:
  instance:
    hostname: sso
    preferIpAddress: true 
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 10.8.0. 
  application:
    name: sso-service

  redis:
    database: 0
    host: redis
    port: 6379
    
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false    
swagger:
  basePackage: com.github.sso.core.web
  title: SSO RESTful API
  desc: SSO RESTFUL API
  serviceUrl: http://www.galaxyinternet.com
  version: 1.0