server:
  context-path: /
  port: 8101
  tomcat:
    access_log_enabled: true
eureka:
  instance:
    hostname: user
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 10.8.0.
    stream:
      bindings:
        input:
          binder: rabbit1
          group: user
        output:
          group: user
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbit
                port: 5672
                username: cloud
                password: cloud
                virtualHost: cloud
                        
  application:
    name: user-service    
 
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://mysql:3306/user_service?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1  
    maxActive: 10  
    initialSize: 1  
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false 
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
            
swagger:
  basePackage: com.github.user.core.web
  title: 用户管理 RESTful API
  desc: 用户管理 RESTFUL API
  serviceUrl: http://www.galaxyinternet.com
  version: 1.0